services:
  - type: web
    name: baby-lucky-valentine
    env: static
    buildCommand: "echo 'No build needed for static site'"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /(.*)/
        destination: /index.html
